/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param title 
 * @param afishaUrl 
 * @param city 
 * @param place 
 * @param address 
 * @param datetime 
 * @param mapUrl 
 * @param images 
 * @param minPrice 
 * @param artists 
 */
data class Concert (

    val title: kotlin.Any,
    val afishaUrl: kotlin.Any,
    val city: kotlin.Any,
    val place: kotlin.Any? = null,
    val address: kotlin.Any,
    val datetime: kotlin.Any,
    val mapUrl: kotlin.Any? = null,
    val images: kotlin.Any,
    val minPrice: kotlin.Any? = null,
    val artists: kotlin.Any
)